# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('forget_password', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_confirm_code', models.IntegerField(default=0)),
                ('mobile_number', models.BigIntegerField()),
                ('profile_pic', models.FileField(default='http://180dc.org/wp-content/uploads/2016/08/default-profile.png', upload_to='')),
                ('user_type', models.CharField(default='Customer', max_length=100)),
                ('Reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_code', models.IntegerField(default=job.models.Customer.my_random_key)),
                ('confirm', models.NullBooleanField(default=False)),
                ('wish_to_be_worker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(default=0.0, max_length=100)),
                ('trasportation_charge', models.FloatField(max_length=100)),
                ('visit_charge', models.FloatField(max_length=100)),
                ('extra_cost', models.FloatField(blank=True, default=0.0, max_length=100, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_description', models.CharField(max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_datetime', models.DateField()),
                ('total_cost', models.FloatField(max_length=100)),
                ('trasportation_charge', models.FloatField(max_length=100)),
                ('visit_charge', models.FloatField(max_length=100)),
                ('extra_cost', models.FloatField(max_length=100)),
                ('invoice_status', models.CharField(default='pending', max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_start_datetime', models.DateTimeField()),
                ('job_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.CharField(max_length=200)),
                ('job_status', models.CharField(default='pending', max_length=20)),
                ('job_report', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_approvel', models.BooleanField(default=False)),
                ('worker_approvel', models.CharField(default=0, max_length=10)),
                ('report_customer_approvel', models.BooleanField(default=True)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('report_admin_approvel', models.BooleanField(default=True)),
                ('payment_approvel', models.CharField(default=0, max_length=30)),
                ('rejection_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('Estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Estimation')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(default=1, max_length=10)),
                ('reciever_type', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('noti_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('query_description', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('query_response', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request', models.CharField(default='', max_length=200)),
                ('service_dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_created', models.BooleanField(default=False)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Category')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='available', max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Worker'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request'),
        ),
    ]
