# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_request',
            name='category_id',
        ),
    ]
