# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('forget_password', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('profile_pic', models.FileField(upload_to='')),
                ('user_type', models.CharField(default='Admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('forget_password', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('profile_pic', models.FileField(upload_to='')),
                ('user_type', models.CharField(default='Customer', max_length=100)),
                ('Reg_date', models.DateField(max_length=100)),
                ('confirmation_code', models.CharField(max_length=100)),
                ('confirm', models.NullBooleanField(default=False)),
            ],
        ),
    ]
