# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_worker_approvel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(max_length=10)),
                ('reciever_type', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
            ],
        ),
    ]
