# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_feedback_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_datetime', models.DateField()),
                ('total_cost', models.FloatField(max_length=100)),
                ('trasportation_charge', models.FloatField(max_length=100)),
                ('visit_charge', models.FloatField(max_length=100)),
                ('extra_cost', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_start_datetime', models.DateField()),
                ('job_end_datetime', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=200)),
                ('job_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('forget_password', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('profile_pic', models.FileField(upload_to='')),
                ('user_type', models.CharField(default='Admin', max_length=100)),
                ('status', models.CharField(default='available', max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer'),
        ),
        migrations.AddField(
            model_name='job',
            name='feedback_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Feedback'),
        ),
        migrations.AddField(
            model_name='job',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Invoice'),
        ),
        migrations.AddField(
            model_name='job',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request'),
        ),
        migrations.AddField(
            model_name='job',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Worker'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request'),
        ),
    ]
