# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20170331_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='target',
            field=models.CharField(max_length=20),
        ),
    ]
