# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170214_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='feedback_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoice_id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
