# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20170331_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='worker_approvel',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
