# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20170214_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(max_length=100)),
                ('trasportation_charge', models.FloatField(max_length=100)),
                ('visit_charge', models.FloatField(max_length=100)),
                ('extra_cost', models.FloatField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Customer')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Services_Request')),
            ],
        ),
    ]
