# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20170331_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_request',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.Category'),
            preserve_default=False,
        ),
    ]
