# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_services_request_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
