# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170214_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Estimate_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.Estimation'),
        ),
    ]
