# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170406_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejection_reason',
            field=models.CharField(default='', max_length=150),
        ),
    ]
