# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
