# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20170214_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
