# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20170214_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='forget_password',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user_type',
        ),
        migrations.AddField(
            model_name='worker',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.Customer'),
            preserve_default=False,
        ),
    ]
