# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20170220_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='services_request',
            name='service_dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
