# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20170223_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_start_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
