# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20170223_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_response',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
