# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_customer_wish_to_be_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_approvel',
            field=models.BooleanField(default=False),
        ),
    ]
