# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_job_customer_approvel'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_request',
            name='job_created',
            field=models.BooleanField(default=False),
        ),
    ]
