# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_services_request_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirmation_code',
            field=models.IntegerField(default=job.models.Customer.my_random_key),
        ),
        migrations.AlterField(
            model_name='customer',
            name='forget_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
