# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_auto_20170301_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_report',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
