# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_job_job_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='report_customer_approvel',
            field=models.BooleanField(default=True),
        ),
    ]
