# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
