# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_auto_20170307_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='forget_password',
            field=models.IntegerField(default=job.models.Customer.my_random_key),
        ),
    ]
