# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_auto_20170314_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp_confirm_code',
            field=models.IntegerField(default=job.models.Customer.my_random_key),
        ),
        migrations.AlterField(
            model_name='customer',
            name='forget_password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
