# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
