# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20170314_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp_confirm_code',
            field=models.IntegerField(default=0),
        ),
    ]
