# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_auto_20170314_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_start_datetime',
            field=models.DateTimeField(),
        ),
    ]
