# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_auto_20170315_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='report_mark_as_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services_request',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(default='http://180dc.org/wp-content/uploads/2016/08/default-profile.png', upload_to=''),
        ),
    ]
