# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_auto_20170320_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='report_mark_as_read',
        ),
        migrations.AddField(
            model_name='job',
            name='report_admin_approvel',
            field=models.BooleanField(default=True),
        ),
    ]
