# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_auto_20170320_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='report_mark_as_read',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_confirm_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='report_admin_approvel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='extra_cost',
            field=models.FloatField(blank=True, default=0.0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='trasportation_charge',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='visit_charge',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_response',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
