# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20170320_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp_confirm_code',
            field=models.IntegerField(default=0),
        ),
    ]
