# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_customer_otp_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='trasportation_charge',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='visit_charge',
            field=models.FloatField(max_length=100),
        ),
    ]
