# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_customer_otp_confirm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
