# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_customer_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
