# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_auto_20170323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='extra_cost',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
