# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_auto_20170323_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='extra_cost',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
