# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_auto_20170323_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='extra_cost',
            field=models.FloatField(blank=True, default=0.0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_response',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
