# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_auto_20170323_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
