# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_customer_id_proof'),
        ('job', '0042_auto_20170323_1831'),
    ]

    operations = [
    ]
