# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_auto_20170403_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
