# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_approvel',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
